sudo: required
dist: xenial
language: cpp

install:
    - sudo add-apt-repository --yes ppa:jonathonf/gcc-7.3
    - sudo apt update -qq
    - sudo apt install -q libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev g++-7


script:
    - mkdir build
    - cd build
    - cmake ..
    - make

